insert into anrede (anrede) values ('Herr');
insert into anrede (anrede) values ('Frau');
insert into anrede (anrede) values ('Firma');
insert into anrede (anrede) values ('Dr.');
insert into anrede (anrede) values ('Prof.');
insert into anrede (anrede) values ('Dr. Med');
insert into anrede (anrede) values ('Familie');
insert into anrede (anrede) values ('-');
insert into funktion (name) values ('Fahrer');
insert into funktion (name) values ('Lagerleiter');
insert into funktion (name) values ('Programm');
insert into funktion (name) values ('Küche');
insert into funktion (name) values ('Gruppenleiter');
insert into geschlecht (name) values ('Herr');
insert into geschlecht (name) values ('Frau');
insert into legendatyp (typ) values ('Wasser');
insert into legendatyp (typ) values ('Besitzer');
insert into legendatyp (typ) values ('Pächter');
insert into legendatyp (typ) values ('Postanschrift');
insert into legendatyp (typ) values ('Förster/Forstamt');
insert into legendatyp (typ) values ('Jagdtpächter');
insert into legendatyp (typ) values ('Ortsvorsteher');
insert into legendatyp (typ) values ('Landratsamt');
insert into legendatyp (typ) values ('Arzt');
insert into legendatyp (typ) values ('Krankenhaus' );
insert into legendatyp (typ) values ('Lebensmittel');
insert into legendatyp (typ) values ('Getränkemarkt');
insert into legendatyp (typ) values ('Bäckerei');
insert into legendatyp (typ) values ('Metzgerei');
insert into legendatyp (typ) values ('Milch');
insert into legendatyp (typ) values ('Holz');
insert into legendatyp (typ) values ('Müll');
insert into legendatyp (typ) values ('Freibad');
insert into legendatyp (typ) values ('Förster');
insert into legendatyp (typ) values ('Doba M');
insert into legendatyp (typ) values ('Doba W');
insert into legendatyp (typ) values ('Biwak 1');
insert into legendatyp (typ) values ('Biwak 2');
insert into legendatyp (typ) values ('Biwak 3');
insert into legendatyp (typ) values ('Biwak 4');
insert into legendatyp (typ) values ('Biwak 5');
insert into legendatyp (typ) values ('Schwimmbad');
insert into legendatyp (typ) values ('Zeltplatz');
insert into legendatyp (typ) values ('Arzt 2');
insert into legendatyp (typ) values ('Sägewerk');
insert into legendatyp (typ) values ('Landrat');
insert into waehrung (waehrung) values ('CHF');
insert into waehrung (waehrung) values ('€');
insert into waehrung (waehrung) values ('DM');
insert into zdbez (bezeichnung) values ('Aufziehseil');
insert into zdbez (bezeichnung) values ('Dach');
insert into zdbez (bezeichnung) values ('Dach für Feuerstelle');
insert into zdbez (bezeichnung) values ('Dach mit Abspannseilen');
insert into zdbez (bezeichnung) values ('Dachplanen');
insert into zdbez (bezeichnung) values ('Einsinkdeckel');
insert into zdbez (bezeichnung) values ('Erdnägel');
insert into zdbez (bezeichnung) values ('Fensterplanen doppelt');
insert into zdbez (bezeichnung) values ('Heringe');
insert into zdbez (bezeichnung) values ('Kette');
insert into zdbez (bezeichnung) values ('Kiste für Seitenstangen');
insert into zdbez (bezeichnung) values ('Metallwinkel (Teleskopierbar)');
insert into zdbez (bezeichnung) values ('Stangenschnur');
insert into zdbez (bezeichnung) values ('Vierecksbahnen doppelt (unter Fenst.)');
insert into zdbez (bezeichnung) values ('Vierecksbahn doppelt');
insert into zdbez (bezeichnung) values ('Zeltsack für Dach');
insert into zdbez (bezeichnung) values ('Eingangsstangen Holz 2fach');
insert into zdbez (bezeichnung) values ('Eingangsstangen Metal 2fach');
insert into zdbez (bezeichnung) values ('Winkel Metal 2fach (teleskopierbar)');
insert into zdbez (bezeichnung) values ('Mittelmast Holz 2fach');
insert into zdbez (bezeichnung) values ('Mittelmast Holz 3fach');
insert into zdbez (bezeichnung) values ('Mittelmast Metall (teleskopierbar)');
insert into zdbez (bezeichnung) values ('Mittelmast Metall 2fach');
insert into zdbez (bezeichnung) values ('Mittelmast Metall 3fach');
insert into zdbez (bezeichnung) values ('Mittelmast Metall 4fach');
insert into zdbez (bezeichnung) values ('Seitenstangen Metall');
insert into zdbez (bezeichnung) values ('Seitenstangen Metall (teleskopierbar)');
insert into zdbez (bezeichnung) values ('Querstangen Metall 3fach');
insert into zdbez (bezeichnung) values ('Querstangen Metall (teleskopierbar)');
insert into zdbez (bezeichnung) values ('Eingangsstangen Metall 3fach');
insert into zdbez (bezeichnung) values ('Jurtenkreuz (3 Einzelteile)');
insert into zdbez (bezeichnung) values ('Abspannseil (Einzel)');
insert into zdbez (bezeichnung) values ('Abspannseil (Doppelt)');
insert into zdbez (bezeichnung) values ('Schrauben');
insert into zdbez (bezeichnung) values ('Kreuzseil');
insert into zdbez (bezeichnung) values ('Theaterbahnen');
insert into zdbez (bezeichnung) values ('Vierecksbahn einzeln');